#!/bin/sh
# load extra modules
SETTINGS="/etc/settings.modules"
MODDIR=/lib/modules/`uname -r`

if [ ! -f $SETTINGS ]; then
        echo "modules: missing $SETTINGS"
        exit 0
fi

. $SETTINGS

if [ $ntfs = "1" ]; then
        echo "init cifs"
        insmod $MODDIR/kernel/fs/ntfs/ntfs.ko
fi

if [ $cifs = "1" ]; then
        echo "init cifs"
        insmod $MODDIR/kernel/fs/cifs/cifs.ko
fi

if [ $zd1211b = "1" ]; then
        echo "init zd1211b"
        insmod $MODDIR/kernel/drivers/net/zd1211b.ko
fi

