# git
SRCREV_pn-enigma2-plugin-skins-magic ?= "${AUTOREV}"
SRCREV_pn-enigma2 ?= "${AUTOREV}"
SRCREV_pn-aio-grab ?= "${AUTOREV}"
SRCREV_pn-ambx ?= "${AUTOREV}"
SRCREV_pn-python-pyambx ?= "${AUTOREV}"
SRCREV_pn-enigma2-plugin-extensions-ambx ?= "${AUTOREV}"
SRCREV_pn-enigma2-pliplugins ?= "${AUTOREV}"
SRCREV_pn-enigma2-plugin-extensions-xmltvimport ?= "${AUTOREV}"
SRCREV_pn-hotplug-e2-helper ?= "${AUTOREV}"

# svn
SRCREV_pn-tuxbox-common ?= "${AUTOREV}"
SRCREV_pn-tuxbox-stream ?= "${AUTOREV}"
SRCREV_pn-tuxbox-plugins-enigma ?= "${AUTOREV}"
SRCREV_pn-tuxterm ?= "${AUTOREV}"
SRCREV_pn-db-epg ?= "${AUTOREV}"
SRCREV_pn-plimgr ?= "${AUTOREV}"
SRCREV_pn-scramble ?= "2"
SRCREV_pn-enigma2-plugin-extensions-tuxcom ?= "${AUTOREV}"
SRCREV_pn-enigma2-plugin-extensions-tuxterm ?= "${AUTOREV}"

# cvs
SRCDATE_enigma2-plugins ?= "20101023"
SRCDATE_enigma2-skins ?= "20101023"
SRCDATE_enigma2-streamproxy ?= "20080728"
SRCDATE_tuxbox-common ?= "20090305"
SRCDATE_tuxbox-libs ?= "20040928"
SRCDATE_libtuxbox ?= "20040928"
SRCDATE_tuxcom-enigma2 ?= "20060123"
SRCDATE_libtuxtxt ?= "20090130"
SRCDATE_tuxbox-plugins ?= "20090601"
SRCDATE_dvbsnoop ?= "20081001"
SRCDATE_libdvbsi++ ?= "20100126"
SRCDATE_inadyn-mt ?= "20100519"
SRCDATE_gst-plugin-dvbmediasink ?= "20100729"

# dm7025
SRCDATE_squashfs-tools-native = "20100319"

# others
SRCDATE_enigma2-plugin-extensions-xmltvimport-rytec ?= "20101117"
SRCDATE_enigma2-plugin-picons-sat ?= "20100628"
SRCDATE_enigma2-plugin-picons-ziggo.casema ?= "20101113"
SRCDATE_enigma2-plugin-picons-ziggo.tvhome ?= "20101113"
SRCDATE_enigma2-plugin-settings-rytec-13e19e23e28e = "20101116"
SRCDATE_enigma2-plugin-settings-rytec-motor = "20101116"
