#!/bin/sh

mount -t tmpfs tmpfs /dev  -o size=64k,mode=0755

mkdir /dev/pts

mount -t devpts devpts /dev/pts

# manually create /dev/null, so mdev can use it in device scripts
mknod /dev/null c 1 3
chmod 666 /dev/null
echo > /dev/mdev.seq

echo "/sbin/mdev" >/proc/sys/kernel/hotplug

touch /dev/.udev

[ -d "/sys/kernel" ] || mount sysfs /sys -t sysfs

mdev -s

if [ -f /etc/mdev/staticdevices.tar.gz ]
then
	tar xzf /etc/mdev/staticdevices.tar.gz -C /dev
fi

