#! /bin/sh 

mkdir -p /dev/dvb /dev/pts /dev/dbox /dev/dvb/adapter0 /dev/loop /dev/i2c /dev/input /dev/sound /dev/fb /dev/vc /dev/mtdblock /dev/mtd /dev/tts

mknod /dev/tty0 c 4 0 
mknod /dev/tty1 c 4 1 
mknod /dev/tty2 c 4 2
mknod /dev/tty3 c 4 3

mknod /dev/watchdog c 10 130

mknod /dev/zero c 1 5

mknod /dev/sound/dsp c 14 3
mknod /dev/sound/mixer c 14 0
mknod /dev/sound/mixer1 c 14 16


mknod /dev/dvb/adapter0/demux4 c 212 68
mknod /dev/dvb/adapter0/dvr4 c 212 69

mknod /dev/input/mouse0 c 13 32

mknod /dev/i2c/0 c 89 0

mknod /dev/sci0 c 10 58
mknod /dev/ci0 c 213 0

touch /dev/dbox/lcd0

echo "Gigablue" > /proc/stb/info/model
 