#!/bin/sh

mount -t tmpfs tmpfs /dev  -o size=64k,mode=0755

mkdir /dev/pts

mount -t devpts devpts /dev/pts

echo "/sbin/mdev" >/proc/sys/kernel/hotplug

touch /dev/.udev

mount -t sysfs sysfs /sys

mdev -s

if [ -f /etc/mdev/staticdevices.tar.gz ]
then
	tar xzf /etc/mdev/staticdevices.tar.gz -C /dev
fi

echo > /dev/mdev.seq
